apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plow
  labels:
    app: plow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plow
    spec:
      containers:
        - image: appscode/plow:canary
          name: plow
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: plow
  labels:
    app: plow
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: plow
