apiVersion: extensions/v1alpha1
kind: Deployment
metadata:
  labels:
    app: plow
  name: plow
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: plow
    spec:
      containers:
      - args:
        - run
        - --v=3
        - --connector=incluster
        image: appscode/plow:0.2.0
        imagePullPolicy: Always
        name: plow
        ports:
        - containerPort: 9855
          name: pt
          protocol: TCP
        - containerPort: 50055
          name: tls
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
            - mountPath: /tmp
              name: chart-volume
      volumes:
        - name: chart-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plow
  namespace: kube-system
  labels:
    app: plow
spec:
  ports:
  - name: pt
    port: 9855
    targetPort: pt
  - name: tls
    port: 50055
    targetPort: web
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: plow
