// Code generated by ./hack/browserify.py
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var _ = require('lodash');

var apis = _.merge({},
    require('./apis/plow/v1alpha1/client.gw.js'),
    require('./apis/plow/v1alpha1/cluster.gw.js'),
    require('./apis/plow/v1alpha1/incident.gw.js'),
    require('./apis/plow/v1alpha1/metadata.gw.js')
);
module.exports = apis.appscode.plow;
