// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package v1alpha1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import appscode_dtypes "github.com/appscode/api/dtypes"
import appscode_version "github.com/appscode/api/version"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ClusterSettings struct {
	LogIndexPrefix string `protobuf:"bytes,1,opt,name=log_index_prefix,json=logIndexPrefix" json:"log_index_prefix,omitempty"`
	// Number of secs logs will be stored in ElasticSearch
	LogStorageLifetime int64 `protobuf:"varint,2,opt,name=log_storage_lifetime,json=logStorageLifetime" json:"log_storage_lifetime,omitempty"`
	// Number of secs logs will be stored in InfluxDB
	MonitoringStorageLifetime int64 `protobuf:"varint,3,opt,name=monitoring_storage_lifetime,json=monitoringStorageLifetime" json:"monitoring_storage_lifetime,omitempty"`
}

func (m *ClusterSettings) Reset()                    { *m = ClusterSettings{} }
func (m *ClusterSettings) String() string            { return proto.CompactTextString(m) }
func (*ClusterSettings) ProtoMessage()               {}
func (*ClusterSettings) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ClusterSettings) GetLogIndexPrefix() string {
	if m != nil {
		return m.LogIndexPrefix
	}
	return ""
}

func (m *ClusterSettings) GetLogStorageLifetime() int64 {
	if m != nil {
		return m.LogStorageLifetime
	}
	return 0
}

func (m *ClusterSettings) GetMonitoringStorageLifetime() int64 {
	if m != nil {
		return m.MonitoringStorageLifetime
	}
	return 0
}

type Cluster struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Provider             string            `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	Os                   string            `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	Region               string            `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,6,opt,name=zone" json:"zone,omitempty"`
	CreatedAt            int64             `protobuf:"varint,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Links                map[string]string `protobuf:"bytes,8,rep,name=links" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DoNotDelete          bool              `protobuf:"varint,9,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	Status               string            `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
	StatusCause          string            `protobuf:"bytes,11,opt,name=status_cause,json=statusCause" json:"status_cause,omitempty"`
	GceProject           string            `protobuf:"bytes,12,opt,name=gce_project,json=gceProject" json:"gce_project,omitempty"`
	KubeletVersion       string            `protobuf:"bytes,13,opt,name=kubelet_version,json=kubeletVersion" json:"kubelet_version,omitempty"`
	SaltbaseVersion      string            `protobuf:"bytes,14,opt,name=saltbase_version,json=saltbaseVersion" json:"saltbase_version,omitempty"`
	KubeStarterVersion   string            `protobuf:"bytes,15,opt,name=kube_starter_version,json=kubeStarterVersion" json:"kube_starter_version,omitempty"`
	NodeCount            int32             `protobuf:"varint,16,opt,name=node_count,json=nodeCount" json:"node_count,omitempty"`
	ApiServerUrl         string            `protobuf:"bytes,17,opt,name=api_server_url,json=apiServerUrl" json:"api_server_url,omitempty"`
	KubeUser             string            `protobuf:"bytes,18,opt,name=kube_user,json=kubeUser" json:"kube_user,omitempty"`
	KubePassword         string            `protobuf:"bytes,19,opt,name=kube_password,json=kubePassword" json:"kube_password,omitempty"`
	CaCert               string            `protobuf:"bytes,20,opt,name=ca_cert,json=caCert" json:"ca_cert,omitempty"`
	KubeBearerToken      string            `protobuf:"bytes,21,opt,name=kube_bearer_token,json=kubeBearerToken" json:"kube_bearer_token,omitempty"`
	Settings             *ClusterSettings  `protobuf:"bytes,22,opt,name=settings" json:"settings,omitempty"`
	InstanceRootPassword string            `protobuf:"bytes,23,opt,name=instance_root_password,json=instanceRootPassword" json:"instance_root_password,omitempty"`
	Version              string            `protobuf:"bytes,24,opt,name=version" json:"version,omitempty"`
	Sku                  string            `protobuf:"bytes,25,opt,name=sku" json:"sku,omitempty"`
	CreatedBy            string            `protobuf:"bytes,26,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	DefaultAccessLevel   string            `protobuf:"bytes,27,opt,name=default_access_level,json=defaultAccessLevel" json:"default_access_level,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Cluster) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Cluster) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Cluster) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Cluster) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Cluster) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Cluster) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Cluster) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *Cluster) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Cluster) GetStatusCause() string {
	if m != nil {
		return m.StatusCause
	}
	return ""
}

func (m *Cluster) GetGceProject() string {
	if m != nil {
		return m.GceProject
	}
	return ""
}

func (m *Cluster) GetKubeletVersion() string {
	if m != nil {
		return m.KubeletVersion
	}
	return ""
}

func (m *Cluster) GetSaltbaseVersion() string {
	if m != nil {
		return m.SaltbaseVersion
	}
	return ""
}

func (m *Cluster) GetKubeStarterVersion() string {
	if m != nil {
		return m.KubeStarterVersion
	}
	return ""
}

func (m *Cluster) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *Cluster) GetApiServerUrl() string {
	if m != nil {
		return m.ApiServerUrl
	}
	return ""
}

func (m *Cluster) GetKubeUser() string {
	if m != nil {
		return m.KubeUser
	}
	return ""
}

func (m *Cluster) GetKubePassword() string {
	if m != nil {
		return m.KubePassword
	}
	return ""
}

func (m *Cluster) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *Cluster) GetKubeBearerToken() string {
	if m != nil {
		return m.KubeBearerToken
	}
	return ""
}

func (m *Cluster) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Cluster) GetInstanceRootPassword() string {
	if m != nil {
		return m.InstanceRootPassword
	}
	return ""
}

func (m *Cluster) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Cluster) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Cluster) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Cluster) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

type ClusterDescribeRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *ClusterDescribeRequest) Reset()                    { *m = ClusterDescribeRequest{} }
func (m *ClusterDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeRequest) ProtoMessage()               {}
func (*ClusterDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ClusterDescribeRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ClusterDescribeResponse struct {
	Cluster      *Cluster                             `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Spec         *ClusterDescribeResponse_ClusterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	OperationUid string                               `protobuf:"bytes,3,opt,name=operation_uid,json=operationUid" json:"operation_uid,omitempty"`
}

func (m *ClusterDescribeResponse) Reset()                    { *m = ClusterDescribeResponse{} }
func (m *ClusterDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse) ProtoMessage()               {}
func (*ClusterDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ClusterDescribeResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClusterDescribeResponse) GetSpec() *ClusterDescribeResponse_ClusterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ClusterDescribeResponse) GetOperationUid() string {
	if m != nil {
		return m.OperationUid
	}
	return ""
}

type ClusterDescribeResponse_ClusterSpec struct {
	ContainerCount int32 `protobuf:"varint,1,opt,name=container_count,json=containerCount" json:"container_count,omitempty"`
	PodCount       int32 `protobuf:"varint,2,opt,name=pod_count,json=podCount" json:"pod_count,omitempty"`
	ServiceCount   int32 `protobuf:"varint,3,opt,name=service_count,json=serviceCount" json:"service_count,omitempty"`
	RcCount        int32 `protobuf:"varint,4,opt,name=rc_count,json=rcCount" json:"rc_count,omitempty"`
	TotalCpu       int64 `protobuf:"varint,5,opt,name=total_cpu,json=totalCpu" json:"total_cpu,omitempty"`
	TotalMemory    int64 `protobuf:"varint,6,opt,name=total_memory,json=totalMemory" json:"total_memory,omitempty"`
}

func (m *ClusterDescribeResponse_ClusterSpec) Reset()         { *m = ClusterDescribeResponse_ClusterSpec{} }
func (m *ClusterDescribeResponse_ClusterSpec) String() string { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse_ClusterSpec) ProtoMessage()    {}
func (*ClusterDescribeResponse_ClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0}
}

func (m *ClusterDescribeResponse_ClusterSpec) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetPodCount() int32 {
	if m != nil {
		return m.PodCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetServiceCount() int32 {
	if m != nil {
		return m.ServiceCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetRcCount() int32 {
	if m != nil {
		return m.RcCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetTotalCpu() int64 {
	if m != nil {
		return m.TotalCpu
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetTotalMemory() int64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

type ClusterListRequest struct {
	Status []string `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
}

func (m *ClusterListRequest) Reset()                    { *m = ClusterListRequest{} }
func (m *ClusterListRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterListRequest) ProtoMessage()               {}
func (*ClusterListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ClusterListRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterListResponse struct {
	Clusters []*Cluster `protobuf:"bytes,1,rep,name=clusters" json:"clusters,omitempty"`
}

func (m *ClusterListResponse) Reset()                    { *m = ClusterListResponse{} }
func (m *ClusterListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterListResponse) ProtoMessage()               {}
func (*ClusterListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ClusterListResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type InstanceGroup struct {
	Sku              string `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Count            int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	UseSpotInstances bool   `protobuf:"varint,3,opt,name=use_spot_instances,json=useSpotInstances" json:"use_spot_instances,omitempty"`
}

func (m *InstanceGroup) Reset()                    { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string            { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()               {}
func (*InstanceGroup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *InstanceGroup) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *InstanceGroup) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *InstanceGroup) GetUseSpotInstances() bool {
	if m != nil {
		return m.UseSpotInstances
	}
	return false
}

type ClusterCreateRequest struct {
	Name              string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Provider          string           `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	Zone              string           `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	CredentialUid     string           `protobuf:"bytes,4,opt,name=credential_uid,json=credentialUid" json:"credential_uid,omitempty"`
	NodeGroups        []*InstanceGroup `protobuf:"bytes,5,rep,name=node_groups,json=nodeGroups" json:"node_groups,omitempty"`
	KubernetesVersion string           `protobuf:"bytes,6,opt,name=kubernetes_version,json=kubernetesVersion" json:"kubernetes_version,omitempty"`
	DoNotDelete       bool             `protobuf:"varint,7,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	// Default access level is to allow permission to the cluster
	// when no Role matched for that specif user or group. This can
	// set as
	//   - kubernetes:team-admin
	//   - kubernetes:cluster-admin
	//   - kubernetes:admin
	//   - kubernetes:editor
	//   - kubernetes:viewer
	//   - deny-access
	// If not set this will set ""
	DefaultAccessLevel string `protobuf:"bytes,8,opt,name=default_access_level,json=defaultAccessLevel" json:"default_access_level,omitempty"`
	GceProject         string `protobuf:"bytes,9,opt,name=gce_project,json=gceProject" json:"gce_project,omitempty"`
}

func (m *ClusterCreateRequest) Reset()                    { *m = ClusterCreateRequest{} }
func (m *ClusterCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterCreateRequest) ProtoMessage()               {}
func (*ClusterCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ClusterCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterCreateRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ClusterCreateRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ClusterCreateRequest) GetCredentialUid() string {
	if m != nil {
		return m.CredentialUid
	}
	return ""
}

func (m *ClusterCreateRequest) GetNodeGroups() []*InstanceGroup {
	if m != nil {
		return m.NodeGroups
	}
	return nil
}

func (m *ClusterCreateRequest) GetKubernetesVersion() string {
	if m != nil {
		return m.KubernetesVersion
	}
	return ""
}

func (m *ClusterCreateRequest) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *ClusterCreateRequest) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

func (m *ClusterCreateRequest) GetGceProject() string {
	if m != nil {
		return m.GceProject
	}
	return ""
}

type ClusterDeleteRequest struct {
	Name                 string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReleaseReservedIp    bool   `protobuf:"varint,2,opt,name=release_reserved_ip,json=releaseReservedIp" json:"release_reserved_ip,omitempty"`
	Force                bool   `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
	KeepLodabalancers    bool   `protobuf:"varint,4,opt,name=keep_lodabalancers,json=keepLodabalancers" json:"keep_lodabalancers,omitempty"`
	DeleteDynamicVolumes bool   `protobuf:"varint,5,opt,name=delete_dynamic_volumes,json=deleteDynamicVolumes" json:"delete_dynamic_volumes,omitempty"`
}

func (m *ClusterDeleteRequest) Reset()                    { *m = ClusterDeleteRequest{} }
func (m *ClusterDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDeleteRequest) ProtoMessage()               {}
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ClusterDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterDeleteRequest) GetReleaseReservedIp() bool {
	if m != nil {
		return m.ReleaseReservedIp
	}
	return false
}

func (m *ClusterDeleteRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *ClusterDeleteRequest) GetKeepLodabalancers() bool {
	if m != nil {
		return m.KeepLodabalancers
	}
	return false
}

func (m *ClusterDeleteRequest) GetDeleteDynamicVolumes() bool {
	if m != nil {
		return m.DeleteDynamicVolumes
	}
	return false
}

type ClusterClientConfigRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterClientConfigRequest) Reset()                    { *m = ClusterClientConfigRequest{} }
func (m *ClusterClientConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigRequest) ProtoMessage()               {}
func (*ClusterClientConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ClusterClientConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClusterClientConfigResponse struct {
	ClusterDomain   string `protobuf:"bytes,1,opt,name=cluster_domain,json=clusterDomain" json:"cluster_domain,omitempty"`
	CaCert          string `protobuf:"bytes,2,opt,name=ca_cert,json=caCert" json:"ca_cert,omitempty"`
	ApiServerUrl    string `protobuf:"bytes,3,opt,name=api_server_url,json=apiServerUrl" json:"api_server_url,omitempty"`
	ClusterUserName string `protobuf:"bytes,4,opt,name=cluster_user_name,json=clusterUserName" json:"cluster_user_name,omitempty"`
	UserCert        string `protobuf:"bytes,5,opt,name=user_cert,json=userCert" json:"user_cert,omitempty"`
	UserKey         string `protobuf:"bytes,6,opt,name=user_key,json=userKey" json:"user_key,omitempty"`
	ContextName     string `protobuf:"bytes,7,opt,name=context_name,json=contextName" json:"context_name,omitempty"`
	UserToken       string `protobuf:"bytes,8,opt,name=user_token,json=userToken" json:"user_token,omitempty"`
	Password        string `protobuf:"bytes,9,opt,name=password" json:"password,omitempty"`
}

func (m *ClusterClientConfigResponse) Reset()                    { *m = ClusterClientConfigResponse{} }
func (m *ClusterClientConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigResponse) ProtoMessage()               {}
func (*ClusterClientConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ClusterClientConfigResponse) GetClusterDomain() string {
	if m != nil {
		return m.ClusterDomain
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetApiServerUrl() string {
	if m != nil {
		return m.ApiServerUrl
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetClusterUserName() string {
	if m != nil {
		return m.ClusterUserName
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserCert() string {
	if m != nil {
		return m.UserCert
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserKey() string {
	if m != nil {
		return m.UserKey
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetContextName() string {
	if m != nil {
		return m.ContextName
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ClusterClientContainerRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DiskName string `protobuf:"bytes,2,opt,name=disk_name,json=diskName" json:"disk_name,omitempty"`
}

func (m *ClusterClientContainerRequest) Reset()                    { *m = ClusterClientContainerRequest{} }
func (m *ClusterClientContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientContainerRequest) ProtoMessage()               {}
func (*ClusterClientContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ClusterClientContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterClientContainerRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

type ClusterInstance struct {
	Uid        string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId" json:"external_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ExternalIp string `protobuf:"bytes,4,opt,name=external_ip,json=externalIp" json:"external_ip,omitempty"`
	InternalIp string `protobuf:"bytes,5,opt,name=internal_ip,json=internalIp" json:"internal_ip,omitempty"`
	Sku        string `protobuf:"bytes,6,opt,name=sku" json:"sku,omitempty"`
}

func (m *ClusterInstance) Reset()                    { *m = ClusterInstance{} }
func (m *ClusterInstance) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstance) ProtoMessage()               {}
func (*ClusterInstance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *ClusterInstance) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ClusterInstance) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *ClusterInstance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterInstance) GetExternalIp() string {
	if m != nil {
		return m.ExternalIp
	}
	return ""
}

func (m *ClusterInstance) GetInternalIp() string {
	if m != nil {
		return m.InternalIp
	}
	return ""
}

func (m *ClusterInstance) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type ClusterUpdateRequest struct {
	Name        string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DoNotDelete bool             `protobuf:"varint,2,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	Settings    *ClusterSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
	// Default access level is to allow permission to the cluster
	// when no Role matched for that specif user or group. This can
	// set as
	//   - kubernetes:team-admin
	//   - kubernetes:cluster-admin
	//   - kubernetes:admin
	//   - kubernetes:editor
	//   - kubernetes:viewer
	//   - deny-access
	DefaultAccessLevel string `protobuf:"bytes,4,opt,name=default_access_level,json=defaultAccessLevel" json:"default_access_level,omitempty"`
}

func (m *ClusterUpdateRequest) Reset()                    { *m = ClusterUpdateRequest{} }
func (m *ClusterUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterUpdateRequest) ProtoMessage()               {}
func (*ClusterUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *ClusterUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterUpdateRequest) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *ClusterUpdateRequest) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ClusterUpdateRequest) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

type ClusterReconfigureRequest struct {
	Name              string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ApplyToMaster     bool   `protobuf:"varint,2,opt,name=apply_to_master,json=applyToMaster" json:"apply_to_master,omitempty"`
	Sku               string `protobuf:"bytes,3,opt,name=sku" json:"sku,omitempty"`
	Count             int64  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	KubernetesVersion string `protobuf:"bytes,5,opt,name=kubernetes_version,json=kubernetesVersion" json:"kubernetes_version,omitempty"`
}

func (m *ClusterReconfigureRequest) Reset()                    { *m = ClusterReconfigureRequest{} }
func (m *ClusterReconfigureRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterReconfigureRequest) ProtoMessage()               {}
func (*ClusterReconfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ClusterReconfigureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetApplyToMaster() bool {
	if m != nil {
		return m.ApplyToMaster
	}
	return false
}

func (m *ClusterReconfigureRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ClusterReconfigureRequest) GetKubernetesVersion() string {
	if m != nil {
		return m.KubernetesVersion
	}
	return ""
}

type ClusterApplyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterApplyRequest) Reset()                    { *m = ClusterApplyRequest{} }
func (m *ClusterApplyRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterApplyRequest) ProtoMessage()               {}
func (*ClusterApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *ClusterApplyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClusterMetadataRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *ClusterMetadataRequest) Reset()                    { *m = ClusterMetadataRequest{} }
func (m *ClusterMetadataRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterMetadataRequest) ProtoMessage()               {}
func (*ClusterMetadataRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *ClusterMetadataRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ClusterMetadataResponse struct {
	KubedConfig     *ClusterMetadataResponse_KubedConfig `protobuf:"bytes,1,opt,name=kubed_config,json=kubedConfig" json:"kubed_config,omitempty"`
	CustomResources []string                             `protobuf:"bytes,2,rep,name=custom_resources,json=customResources" json:"custom_resources,omitempty"`
}

func (m *ClusterMetadataResponse) Reset()                    { *m = ClusterMetadataResponse{} }
func (m *ClusterMetadataResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterMetadataResponse) ProtoMessage()               {}
func (*ClusterMetadataResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *ClusterMetadataResponse) GetKubedConfig() *ClusterMetadataResponse_KubedConfig {
	if m != nil {
		return m.KubedConfig
	}
	return nil
}

func (m *ClusterMetadataResponse) GetCustomResources() []string {
	if m != nil {
		return m.CustomResources
	}
	return nil
}

type ClusterMetadataResponse_KubedConfig struct {
	Version             *appscode_version.Version `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	OperatorNamespace   string                    `protobuf:"bytes,2,opt,name=operator_namespace,json=operatorNamespace" json:"operator_namespace,omitempty"`
	SearchEnabled       bool                      `protobuf:"varint,3,opt,name=search_enabled,json=searchEnabled" json:"search_enabled,omitempty"`
	ReverseIndexEnabled bool                      `protobuf:"varint,4,opt,name=reverse_index_enabled,json=reverseIndexEnabled" json:"reverse_index_enabled,omitempty"`
	AnalyticsEnabled    bool                      `protobuf:"varint,5,opt,name=analytics_enabled,json=analyticsEnabled" json:"analytics_enabled,omitempty"`
}

func (m *ClusterMetadataResponse_KubedConfig) Reset()         { *m = ClusterMetadataResponse_KubedConfig{} }
func (m *ClusterMetadataResponse_KubedConfig) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadataResponse_KubedConfig) ProtoMessage()    {}
func (*ClusterMetadataResponse_KubedConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{17, 0}
}

func (m *ClusterMetadataResponse_KubedConfig) GetVersion() *appscode_version.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ClusterMetadataResponse_KubedConfig) GetOperatorNamespace() string {
	if m != nil {
		return m.OperatorNamespace
	}
	return ""
}

func (m *ClusterMetadataResponse_KubedConfig) GetSearchEnabled() bool {
	if m != nil {
		return m.SearchEnabled
	}
	return false
}

func (m *ClusterMetadataResponse_KubedConfig) GetReverseIndexEnabled() bool {
	if m != nil {
		return m.ReverseIndexEnabled
	}
	return false
}

func (m *ClusterMetadataResponse_KubedConfig) GetAnalyticsEnabled() bool {
	if m != nil {
		return m.AnalyticsEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*ClusterSettings)(nil), "appscode.plow.v1alpha1.ClusterSettings")
	proto.RegisterType((*Cluster)(nil), "appscode.plow.v1alpha1.Cluster")
	proto.RegisterType((*ClusterDescribeRequest)(nil), "appscode.plow.v1alpha1.ClusterDescribeRequest")
	proto.RegisterType((*ClusterDescribeResponse)(nil), "appscode.plow.v1alpha1.ClusterDescribeResponse")
	proto.RegisterType((*ClusterDescribeResponse_ClusterSpec)(nil), "appscode.plow.v1alpha1.ClusterDescribeResponse.ClusterSpec")
	proto.RegisterType((*ClusterListRequest)(nil), "appscode.plow.v1alpha1.ClusterListRequest")
	proto.RegisterType((*ClusterListResponse)(nil), "appscode.plow.v1alpha1.ClusterListResponse")
	proto.RegisterType((*InstanceGroup)(nil), "appscode.plow.v1alpha1.InstanceGroup")
	proto.RegisterType((*ClusterCreateRequest)(nil), "appscode.plow.v1alpha1.ClusterCreateRequest")
	proto.RegisterType((*ClusterDeleteRequest)(nil), "appscode.plow.v1alpha1.ClusterDeleteRequest")
	proto.RegisterType((*ClusterClientConfigRequest)(nil), "appscode.plow.v1alpha1.ClusterClientConfigRequest")
	proto.RegisterType((*ClusterClientConfigResponse)(nil), "appscode.plow.v1alpha1.ClusterClientConfigResponse")
	proto.RegisterType((*ClusterClientContainerRequest)(nil), "appscode.plow.v1alpha1.ClusterClientContainerRequest")
	proto.RegisterType((*ClusterInstance)(nil), "appscode.plow.v1alpha1.ClusterInstance")
	proto.RegisterType((*ClusterUpdateRequest)(nil), "appscode.plow.v1alpha1.ClusterUpdateRequest")
	proto.RegisterType((*ClusterReconfigureRequest)(nil), "appscode.plow.v1alpha1.ClusterReconfigureRequest")
	proto.RegisterType((*ClusterApplyRequest)(nil), "appscode.plow.v1alpha1.ClusterApplyRequest")
	proto.RegisterType((*ClusterMetadataRequest)(nil), "appscode.plow.v1alpha1.ClusterMetadataRequest")
	proto.RegisterType((*ClusterMetadataResponse)(nil), "appscode.plow.v1alpha1.ClusterMetadataResponse")
	proto.RegisterType((*ClusterMetadataResponse_KubedConfig)(nil), "appscode.plow.v1alpha1.ClusterMetadataResponse.KubedConfig")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Clusters service

type ClustersClient interface {
	List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error)
	Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error)
	Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
	Reconfigure(ctx context.Context, in *ClusterReconfigureRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	Apply(ctx context.Context, in *ClusterApplyRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error)
	Metadata(ctx context.Context, in *ClusterMetadataRequest, opts ...grpc.CallOption) (*ClusterMetadataResponse, error)
}

type clustersClient struct {
	cc *grpc.ClientConn
}

func NewClustersClient(cc *grpc.ClientConn) ClustersClient {
	return &clustersClient{cc}
}

func (c *clustersClient) List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error) {
	out := new(ClusterListResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error) {
	out := new(ClusterDescribeResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Reconfigure(ctx context.Context, in *ClusterReconfigureRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Reconfigure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Apply(ctx context.Context, in *ClusterApplyRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error) {
	out := new(ClusterClientConfigResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/ClientConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Metadata(ctx context.Context, in *ClusterMetadataRequest, opts ...grpc.CallOption) (*ClusterMetadataResponse, error) {
	out := new(ClusterMetadataResponse)
	err := grpc.Invoke(ctx, "/appscode.plow.v1alpha1.Clusters/Metadata", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Clusters service

type ClustersServer interface {
	List(context.Context, *ClusterListRequest) (*ClusterListResponse, error)
	Describe(context.Context, *ClusterDescribeRequest) (*ClusterDescribeResponse, error)
	Create(context.Context, *ClusterCreateRequest) (*appscode_dtypes.LongRunningResponse, error)
	Update(context.Context, *ClusterUpdateRequest) (*appscode_dtypes.VoidResponse, error)
	Reconfigure(context.Context, *ClusterReconfigureRequest) (*appscode_dtypes.LongRunningResponse, error)
	Apply(context.Context, *ClusterApplyRequest) (*appscode_dtypes.LongRunningResponse, error)
	Delete(context.Context, *ClusterDeleteRequest) (*appscode_dtypes.LongRunningResponse, error)
	ClientConfig(context.Context, *ClusterClientConfigRequest) (*ClusterClientConfigResponse, error)
	Metadata(context.Context, *ClusterMetadataRequest) (*ClusterMetadataResponse, error)
}

func RegisterClustersServer(s *grpc.Server, srv ClustersServer) {
	s.RegisterService(&_Clusters_serviceDesc, srv)
}

func _Clusters_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).List(ctx, req.(*ClusterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Describe(ctx, req.(*ClusterDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Create(ctx, req.(*ClusterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Update(ctx, req.(*ClusterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Reconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterReconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Reconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Reconfigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Reconfigure(ctx, req.(*ClusterReconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Apply(ctx, req.(*ClusterApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Delete(ctx, req.(*ClusterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_ClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).ClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/ClientConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).ClientConfig(ctx, req.(*ClusterClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.plow.v1alpha1.Clusters/Metadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Metadata(ctx, req.(*ClusterMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clusters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.plow.v1alpha1.Clusters",
	HandlerType: (*ClustersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Clusters_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Clusters_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Clusters_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Clusters_Update_Handler,
		},
		{
			MethodName: "Reconfigure",
			Handler:    _Clusters_Reconfigure_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Clusters_Apply_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Clusters_Delete_Handler,
		},
		{
			MethodName: "ClientConfig",
			Handler:    _Clusters_ClientConfig_Handler,
		},
		{
			MethodName: "Metadata",
			Handler:    _Clusters_Metadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 2057 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x4f, 0x73, 0x1c, 0x47,
	0x15, 0xaf, 0xd9, 0x95, 0xb4, 0xb3, 0x6f, 0xf5, 0xb7, 0xad, 0x38, 0xa3, 0x55, 0x6c, 0x2b, 0x63,
	0x9b, 0x28, 0xb2, 0xbd, 0xb2, 0xe4, 0x14, 0x24, 0x0e, 0x05, 0x58, 0x72, 0x00, 0x55, 0x64, 0xa3,
	0x1a, 0x45, 0x3e, 0x70, 0x60, 0xaa, 0x35, 0xd3, 0xda, 0x4c, 0x34, 0x3b, 0x3d, 0x74, 0xf7, 0x28,
	0x5e, 0xa8, 0x5c, 0x72, 0xcd, 0x81, 0x03, 0x67, 0x52, 0x9c, 0x38, 0x01, 0xc5, 0x85, 0x2a, 0xbe,
	0x40, 0x3e, 0x41, 0x8a, 0x6f, 0xc0, 0x91, 0x2a, 0xce, 0xdc, 0xa8, 0xfe, 0x37, 0x33, 0xd2, 0x6a,
	0xb5, 0x0a, 0x17, 0x69, 0xfa, 0xfd, 0xe9, 0xfe, 0xcd, 0xeb, 0xf7, 0x7e, 0xef, 0xcd, 0xc2, 0x5c,
	0x94, 0x16, 0x5c, 0x10, 0xd6, 0xcb, 0x19, 0x15, 0x14, 0xdd, 0xc4, 0x79, 0xce, 0x23, 0x1a, 0x93,
	0x5e, 0x9e, 0xd2, 0xcf, 0x7b, 0x67, 0x5b, 0x38, 0xcd, 0x3f, 0xc5, 0x5b, 0xdd, 0xb7, 0xfa, 0x94,
	0xf6, 0x53, 0xb2, 0x89, 0xf3, 0x64, 0x13, 0x67, 0x19, 0x15, 0x58, 0x24, 0x34, 0xe3, 0xda, 0xab,
	0x7b, 0xdb, 0x7a, 0x8d, 0xd1, 0xdf, 0x39, 0xa7, 0x8f, 0xc5, 0x30, 0x27, 0x7c, 0x53, 0xfd, 0x35,
	0x06, 0xfe, 0x39, 0x83, 0x33, 0xc2, 0x78, 0x42, 0x33, 0xfb, 0x5f, 0xdb, 0xf8, 0x7f, 0x71, 0x60,
	0x61, 0x57, 0x83, 0x3d, 0x24, 0x42, 0x24, 0x59, 0x9f, 0xa3, 0x75, 0x58, 0x4c, 0x69, 0x3f, 0x4c,
	0xb2, 0x98, 0xbc, 0x0e, 0x73, 0x46, 0x4e, 0x92, 0xd7, 0x9e, 0xb3, 0xe6, 0xac, 0xb7, 0x83, 0xf9,
	0x94, 0xf6, 0xf7, 0xa4, 0xf8, 0x40, 0x49, 0xd1, 0x63, 0x58, 0x96, 0x96, 0x5c, 0x50, 0x86, 0xfb,
	0x24, 0x4c, 0x93, 0x13, 0x22, 0x92, 0x01, 0xf1, 0x1a, 0x6b, 0xce, 0x7a, 0x33, 0x40, 0x29, 0xed,
	0x1f, 0x6a, 0xd5, 0xbe, 0xd1, 0xa0, 0x1f, 0xc1, 0xea, 0x80, 0x66, 0x89, 0xa0, 0x2c, 0xc9, 0x2e,
	0x71, 0x6c, 0x2a, 0xc7, 0x95, 0xca, 0xe4, 0x82, 0xbf, 0xff, 0xef, 0x16, 0xb4, 0x0c, 0x5e, 0xb4,
	0x08, 0xcd, 0x22, 0x89, 0x0d, 0x34, 0xf9, 0x88, 0x10, 0x4c, 0x65, 0xd8, 0x9c, 0xdf, 0x0e, 0xd4,
	0x33, 0xea, 0x82, 0x9b, 0x33, 0x7a, 0x96, 0xc4, 0x84, 0xa9, 0xed, 0xdb, 0x41, 0xb9, 0x46, 0xf3,
	0xd0, 0xa0, 0xdc, 0x9b, 0x52, 0xd2, 0x06, 0xe5, 0xe8, 0x26, 0xcc, 0x30, 0xd2, 0x4f, 0x68, 0xe6,
	0x4d, 0x2b, 0x99, 0x59, 0xc9, 0x7d, 0x7f, 0x43, 0x33, 0xe2, 0xcd, 0xe8, 0x7d, 0xe5, 0x33, 0xba,
	0x05, 0x10, 0x31, 0x82, 0x05, 0x89, 0x43, 0x2c, 0xbc, 0x96, 0x02, 0xde, 0x36, 0x92, 0x67, 0x02,
	0xfd, 0x04, 0xa6, 0xd3, 0x24, 0x3b, 0xe5, 0x9e, 0xbb, 0xd6, 0x5c, 0xef, 0x6c, 0x6f, 0xf4, 0x2e,
	0xcf, 0x81, 0x9e, 0x79, 0x99, 0xde, 0xbe, 0x34, 0xfe, 0x28, 0x13, 0x6c, 0x18, 0x68, 0x47, 0xe4,
	0xc3, 0x5c, 0x4c, 0xc3, 0x8c, 0x8a, 0x30, 0x26, 0x29, 0x11, 0xc4, 0x6b, 0xaf, 0x39, 0xeb, 0x6e,
	0xd0, 0x89, 0xe9, 0x4b, 0x2a, 0x9e, 0x2b, 0x91, 0x04, 0xcc, 0x05, 0x16, 0x05, 0xf7, 0x40, 0x03,
	0xd6, 0x2b, 0xf4, 0x36, 0xcc, 0xea, 0xa7, 0x30, 0xc2, 0x05, 0x27, 0x5e, 0x47, 0x69, 0x3b, 0x5a,
	0xb6, 0x2b, 0x45, 0xe8, 0x0e, 0x74, 0xfa, 0x11, 0x09, 0x73, 0x46, 0x3f, 0x23, 0x91, 0xf0, 0x66,
	0x95, 0x05, 0xf4, 0x23, 0x72, 0xa0, 0x25, 0xe8, 0x1d, 0x58, 0x38, 0x2d, 0x8e, 0xe5, 0x39, 0xa1,
	0xc9, 0x19, 0x6f, 0x4e, 0x67, 0x81, 0x11, 0xbf, 0xd2, 0x52, 0xf4, 0x2e, 0x2c, 0x72, 0x9c, 0x8a,
	0x63, 0xcc, 0x49, 0x69, 0x39, 0xaf, 0x2c, 0x17, 0xac, 0xdc, 0x9a, 0x3e, 0x86, 0x65, 0xe9, 0x1c,
	0x72, 0x81, 0x99, 0x20, 0xac, 0x34, 0x5f, 0x50, 0xe6, 0x48, 0xea, 0x0e, 0xb5, 0xca, 0x7a, 0xdc,
	0x02, 0xc8, 0x68, 0x4c, 0xc2, 0x88, 0x16, 0x99, 0xf0, 0x16, 0xd7, 0x9c, 0xf5, 0xe9, 0xa0, 0x2d,
	0x25, 0xbb, 0x52, 0x80, 0xee, 0xc1, 0x3c, 0xce, 0x93, 0x90, 0x13, 0x76, 0x46, 0x58, 0x58, 0xb0,
	0xd4, 0x5b, 0x52, 0x5b, 0xcd, 0xe2, 0x3c, 0x39, 0x54, 0xc2, 0x23, 0x96, 0xa2, 0x55, 0x68, 0xab,
	0x63, 0x0b, 0x4e, 0x98, 0x87, 0x74, 0x12, 0x48, 0xc1, 0x11, 0x27, 0x0c, 0xdd, 0x85, 0x39, 0xa5,
	0xcc, 0x31, 0xe7, 0x9f, 0x53, 0x16, 0x7b, 0x37, 0xf4, 0x0e, 0x52, 0x78, 0x60, 0x64, 0xe8, 0x4d,
	0x68, 0x45, 0x38, 0x8c, 0x08, 0x13, 0xde, 0xb2, 0x8e, 0x74, 0x84, 0x77, 0x09, 0x13, 0x68, 0x03,
	0x96, 0x94, 0xf7, 0x31, 0xc1, 0x8c, 0xb0, 0x50, 0xd0, 0x53, 0x92, 0x79, 0x6f, 0xe8, 0xb7, 0x97,
	0x8a, 0x1d, 0x25, 0xff, 0x44, 0x8a, 0xd1, 0x2e, 0xb8, 0xdc, 0x14, 0x99, 0x77, 0x73, 0xcd, 0x59,
	0xef, 0x6c, 0xbf, 0x33, 0x21, 0x2d, 0x6c, 0x4d, 0x06, 0xa5, 0x23, 0x7a, 0x0f, 0x6e, 0x26, 0x19,
	0x17, 0x38, 0x8b, 0x48, 0xc8, 0x28, 0x15, 0x15, 0xee, 0x37, 0xd5, 0xa9, 0xcb, 0x56, 0x1b, 0x50,
	0x2a, 0x4a, 0xfc, 0x1e, 0xb4, 0x6c, 0xac, 0x3d, 0x65, 0x66, 0x97, 0xb2, 0x8a, 0xf8, 0x69, 0xe1,
	0xad, 0xe8, 0x2a, 0xe2, 0xa7, 0x45, 0x3d, 0xb3, 0x8f, 0x87, 0x5e, 0x57, 0x29, 0x6c, 0x66, 0xef,
	0x0c, 0xe5, 0x1d, 0xc6, 0xe4, 0x04, 0x17, 0xa9, 0x08, 0x71, 0x14, 0x11, 0xce, 0xc3, 0x94, 0x9c,
	0x91, 0xd4, 0x5b, 0xd5, 0x77, 0x68, 0x74, 0xcf, 0x94, 0x6a, 0x5f, 0x6a, 0xba, 0xef, 0x03, 0x54,
	0xe9, 0x2d, 0x0f, 0x3c, 0x25, 0x43, 0x5b, 0xb6, 0xa7, 0x64, 0x88, 0x96, 0x61, 0xfa, 0x0c, 0xa7,
	0x85, 0xad, 0x5b, 0xbd, 0x78, 0xda, 0x78, 0xdf, 0xf1, 0x37, 0xe0, 0xa6, 0x89, 0xc4, 0x73, 0xc2,
	0x23, 0x96, 0x1c, 0x93, 0x80, 0xfc, 0xba, 0x20, 0x5c, 0x8c, 0x16, 0xbf, 0xff, 0xc7, 0x26, 0xbc,
	0x39, 0x62, 0xcc, 0x73, 0x9a, 0x71, 0x82, 0x3e, 0x80, 0x96, 0xa1, 0x64, 0xe5, 0xd1, 0xd9, 0xbe,
	0x33, 0x21, 0xf0, 0x81, 0xb5, 0x47, 0xbf, 0x80, 0x29, 0x9e, 0x93, 0x48, 0x61, 0xeb, 0x6c, 0x7f,
	0x38, 0xc1, 0xef, 0xe2, 0xc9, 0xe5, 0x45, 0xe6, 0x24, 0x0a, 0xd4, 0x46, 0x32, 0xdf, 0x68, 0x4e,
	0x98, 0xe2, 0xf2, 0x50, 0xbe, 0x83, 0x66, 0xa5, 0xd9, 0x52, 0x78, 0x94, 0xc4, 0xdd, 0x6f, 0x1d,
	0xe8, 0xd4, 0x5c, 0x65, 0x31, 0x46, 0x34, 0x13, 0x38, 0xc9, 0x08, 0x33, 0xb5, 0xe0, 0xa8, 0x5a,
	0x98, 0x2f, 0xc5, 0xba, 0x20, 0x56, 0xa1, 0x9d, 0xd3, 0xd8, 0x98, 0x34, 0x94, 0x89, 0x9b, 0xd3,
	0x58, 0x2b, 0xef, 0xc2, 0x9c, 0xac, 0x94, 0x24, 0xb2, 0xf5, 0xd4, 0x54, 0x06, 0xb3, 0x46, 0xa8,
	0x8d, 0x56, 0xc0, 0x65, 0x91, 0xd1, 0x4f, 0x29, 0x7d, 0x8b, 0x45, 0xe5, 0xe6, 0x82, 0x0a, 0x9c,
	0x86, 0x51, 0x5e, 0x28, 0x8a, 0x6c, 0x06, 0xae, 0x12, 0xec, 0xe6, 0x85, 0xe4, 0x1c, 0xad, 0x1c,
	0x90, 0x01, 0x65, 0x43, 0x45, 0x96, 0xcd, 0xa0, 0xa3, 0x64, 0x2f, 0x94, 0xc8, 0x7f, 0x08, 0xc8,
	0xbc, 0xd4, 0x7e, 0xc2, 0x85, 0xbd, 0xca, 0x8a, 0xc4, 0x9c, 0xb5, 0x66, 0x45, 0x62, 0x7e, 0x00,
	0x37, 0xce, 0x59, 0x9b, 0xbb, 0xfc, 0x10, 0x5c, 0x73, 0x37, 0xda, 0xe1, 0x1a, 0x97, 0x59, 0x3a,
	0xf8, 0x04, 0xe6, 0xf6, 0x4c, 0x7d, 0xfc, 0x8c, 0xd1, 0x22, 0xb7, 0xe9, 0xef, 0x54, 0xe9, 0xbf,
	0x0c, 0xd3, 0x55, 0xf4, 0x9a, 0x81, 0x5e, 0xa0, 0x87, 0x80, 0x0a, 0x4e, 0x42, 0x9e, 0x53, 0x11,
	0xda, 0x0a, 0xe3, 0x2a, 0x7e, 0x6e, 0xb0, 0x58, 0x70, 0x72, 0x98, 0x53, 0x61, 0x77, 0xe6, 0xfe,
	0x7f, 0x1a, 0xb0, 0x6c, 0x0e, 0xdf, 0x55, 0x85, 0x63, 0xdf, 0xd5, 0x76, 0x28, 0x67, 0x4c, 0x87,
	0x6a, 0x5c, 0xe8, 0x50, 0xb6, 0xf3, 0x34, 0x6b, 0x9d, 0xe7, 0x3e, 0xcc, 0x47, 0x8c, 0xc4, 0x24,
	0x13, 0x09, 0x4e, 0x55, 0x06, 0xe9, 0x0e, 0x36, 0x57, 0x49, 0x8f, 0x92, 0x18, 0xfd, 0x14, 0x3a,
	0x8a, 0x39, 0xfb, 0xf2, 0x3d, 0xb9, 0x37, 0xad, 0x42, 0x75, 0x7f, 0x5c, 0xa8, 0xce, 0x45, 0x25,
	0x50, 0x9c, 0xab, 0x1e, 0x39, 0x7a, 0x04, 0x8a, 0x97, 0x59, 0x46, 0x04, 0xe1, 0x25, 0x63, 0xeb,
	0x56, 0xb8, 0x54, 0x69, 0x2c, 0x61, 0x8f, 0xb4, 0xad, 0xd6, 0x68, 0xdb, 0x1a, 0x47, 0x21, 0xee,
	0x38, 0x0a, 0xb9, 0xd8, 0xad, 0xda, 0x17, 0xbb, 0x95, 0xff, 0x4f, 0xa7, 0x8c, 0xb8, 0x3e, 0xe4,
	0xaa, 0x88, 0xf7, 0xe0, 0x06, 0x23, 0x29, 0x91, 0x0d, 0x8b, 0x11, 0xd5, 0x3b, 0xe2, 0x30, 0xc9,
	0x55, 0xf0, 0xdd, 0x60, 0xc9, 0xa8, 0x02, 0xa3, 0xd9, 0xcb, 0x65, 0x4a, 0x9c, 0x50, 0x16, 0x11,
	0x73, 0xdf, 0x7a, 0xa1, 0x02, 0x43, 0x48, 0x1e, 0xa6, 0x34, 0xc6, 0xc7, 0x38, 0x95, 0xd1, 0x63,
	0x7a, 0x9a, 0x70, 0x83, 0x25, 0xa9, 0xd9, 0xaf, 0x2b, 0x24, 0x71, 0xeb, 0x88, 0x84, 0xf1, 0x30,
	0xc3, 0x83, 0x24, 0x0a, 0xcf, 0x68, 0x5a, 0x0c, 0x08, 0x57, 0x95, 0xe4, 0x06, 0xcb, 0x5a, 0xfb,
	0x5c, 0x2b, 0x5f, 0x69, 0x9d, 0xff, 0x18, 0xba, 0x36, 0x91, 0xd2, 0x84, 0x64, 0x62, 0x97, 0x66,
	0x27, 0x49, 0xff, 0x8a, 0x97, 0xf3, 0xbf, 0x69, 0xc0, 0xea, 0xa5, 0x2e, 0xa6, 0x7e, 0x64, 0xfa,
	0x68, 0x75, 0x18, 0xd3, 0x01, 0x4e, 0x32, 0xe3, 0x6d, 0x87, 0xd6, 0xe7, 0x4a, 0x58, 0xef, 0x78,
	0x8d, 0x73, 0x1d, 0x6f, 0xb4, 0xe5, 0x36, 0x2f, 0x69, 0xb9, 0x1b, 0xb0, 0x64, 0x4f, 0x91, 0x5d,
	0x37, 0x54, 0x30, 0x75, 0x9e, 0x2e, 0x18, 0x85, 0xec, 0xbe, 0x2f, 0xe5, 0x75, 0xac, 0x42, 0x5b,
	0xd9, 0xa8, 0xc3, 0xf4, 0xe4, 0xe5, 0x4a, 0x81, 0x3a, 0x6e, 0x05, 0xd4, 0x73, 0x28, 0x7b, 0x86,
	0x4e, 0xba, 0x96, 0x5c, 0x7f, 0x4c, 0x86, 0x92, 0x71, 0x24, 0xfb, 0x91, 0xd7, 0x42, 0x6f, 0xdf,
	0xd2, 0x53, 0x8e, 0x91, 0xa9, 0xad, 0x6f, 0x01, 0x28, 0x6f, 0xdd, 0x97, 0x75, 0x7e, 0xa9, 0xc3,
	0x74, 0x47, 0x96, 0xa5, 0x67, 0xdb, 0x67, 0xdb, 0x94, 0x9e, 0x59, 0xfb, 0x07, 0x70, 0xeb, 0x62,
	0x18, 0x35, 0xd1, 0x5e, 0x95, 0x59, 0xab, 0xd0, 0x8e, 0x13, 0x7e, 0x1a, 0xd6, 0xc6, 0x50, 0x57,
	0x0a, 0x24, 0x18, 0xff, 0xcf, 0xd5, 0xb0, 0x6d, 0xcb, 0xed, 0x92, 0x21, 0xf6, 0x0e, 0x74, 0xc8,
	0x6b, 0x41, 0x58, 0x86, 0xd3, 0x30, 0x89, 0xcd, 0x26, 0x60, 0x45, 0x7b, 0xd5, 0x94, 0xdb, 0xac,
	0x9d, 0x7b, 0xce, 0x29, 0x37, 0x81, 0xae, 0x9c, 0x72, 0x69, 0x90, 0x64, 0x95, 0x81, 0x8e, 0x32,
	0x58, 0xd1, 0x5e, 0x49, 0x84, 0x33, 0x25, 0x11, 0xfa, 0xdf, 0x54, 0x25, 0x75, 0x94, 0xc7, 0x13,
	0x48, 0x6c, 0xa4, 0xec, 0x1b, 0xa3, 0x65, 0x5f, 0x9f, 0x7f, 0x9a, 0xff, 0xef, 0xfc, 0x33, 0x8e,
	0x3b, 0xa6, 0xc6, 0x71, 0x87, 0xff, 0x57, 0x07, 0x56, 0x6c, 0x27, 0x20, 0x91, 0x2a, 0x86, 0x82,
	0x5d, 0xf9, 0x32, 0xdf, 0x83, 0x05, 0x9c, 0xe7, 0xe9, 0x30, 0x14, 0x34, 0x1c, 0x60, 0x35, 0x36,
	0xe8, 0xd7, 0x99, 0x53, 0xe2, 0x4f, 0xe8, 0x0b, 0x6c, 0xbf, 0x40, 0x64, 0xcc, 0x9a, 0x97, 0x34,
	0x8f, 0xa9, 0x7a, 0xf3, 0xb8, 0x9c, 0x42, 0xa7, 0xc7, 0x50, 0xa8, 0xff, 0x6e, 0xd9, 0xf8, 0x9e,
	0xc9, 0xe3, 0xae, 0x2a, 0xf6, 0x6a, 0x40, 0x7a, 0x41, 0x04, 0x8e, 0xb1, 0xc0, 0xd7, 0x1a, 0x90,
	0x2a, 0x63, 0x43, 0x0a, 0xbf, 0x02, 0x35, 0xef, 0xca, 0xc1, 0x41, 0xc6, 0xc7, 0x4c, 0x49, 0x93,
	0xa6, 0x9d, 0x8b, 0xdb, 0xf4, 0x3e, 0x96, 0x7b, 0x18, 0xbe, 0xe9, 0x9c, 0x56, 0x0b, 0xf9, 0x8d,
	0x10, 0x15, 0x5c, 0xd0, 0x81, 0x24, 0x5c, 0x5a, 0x30, 0xd9, 0x3c, 0x1b, 0xaa, 0xdb, 0x2f, 0x68,
	0x79, 0x60, 0xc5, 0xdd, 0xff, 0x3a, 0xd0, 0xa9, 0xed, 0x83, 0x9e, 0x54, 0xa3, 0xab, 0x46, 0xb5,
	0x52, 0xa1, 0xb2, 0x1f, 0xb3, 0x26, 0x72, 0xd5, 0x54, 0xfb, 0x08, 0x90, 0x9e, 0xa7, 0xa8, 0xa6,
	0x1e, 0x9e, 0xe3, 0xc8, 0x16, 0xe4, 0x92, 0xd5, 0xbc, 0xb4, 0x0a, 0xc9, 0x89, 0x9c, 0x60, 0x16,
	0x7d, 0x1a, 0x92, 0x0c, 0x1f, 0xa7, 0x24, 0x36, 0x4c, 0x3f, 0xa7, 0xa5, 0x1f, 0x69, 0x21, 0xda,
	0x86, 0x37, 0x18, 0x91, 0x47, 0x10, 0xf3, 0x75, 0x6c, 0xad, 0x35, 0xe9, 0xdf, 0x30, 0x4a, 0xf5,
	0x89, 0x6c, 0x7d, 0x1e, 0xc0, 0x12, 0xce, 0x70, 0x3a, 0x14, 0x49, 0xc4, 0x4b, 0x7b, 0xcd, 0xf8,
	0x8b, 0xa5, 0xc2, 0x18, 0x6f, 0x7f, 0xdd, 0x01, 0xd7, 0xc4, 0x96, 0xa3, 0xaf, 0x1c, 0x98, 0x92,
	0x93, 0x0f, 0x9a, 0xf4, 0xf1, 0x58, 0x1b, 0xa6, 0xba, 0x0f, 0xae, 0x65, 0xab, 0xaf, 0xcb, 0xdf,
	0xf8, 0xf2, 0xef, 0x5e, 0xc3, 0x75, 0xbe, 0xfc, 0xf6, 0x5f, 0xbf, 0x6f, 0xdc, 0x46, 0x6f, 0x6d,
	0x4a, 0x8f, 0x4d, 0xeb, 0xb1, 0x69, 0x87, 0xa6, 0xcd, 0xcf, 0x38, 0xcd, 0xd0, 0x1f, 0x1c, 0x70,
	0xed, 0x74, 0x8b, 0x7a, 0xd7, 0x1e, 0x83, 0x35, 0xaa, 0xcd, 0xef, 0x38, 0x36, 0xfb, 0x8f, 0x6b,
	0xc8, 0xee, 0x21, 0x7f, 0x1c, 0xb2, 0xdf, 0x16, 0x49, 0xfc, 0x85, 0xc6, 0xf7, 0x95, 0x03, 0x33,
	0x7a, 0xd6, 0x42, 0x0f, 0x27, 0x9c, 0x76, 0x6e, 0x24, 0xeb, 0xde, 0xab, 0xac, 0xf5, 0x8f, 0x28,
	0xbd, 0x7d, 0x9a, 0xf5, 0x83, 0x22, 0xcb, 0x92, 0xac, 0xec, 0x9a, 0xfe, 0xa3, 0x1a, 0xa0, 0xb7,
	0xfd, 0x2b, 0x43, 0xf5, 0xd4, 0xd9, 0x50, 0x68, 0x34, 0x69, 0x4e, 0x44, 0x73, 0x8e, 0x5b, 0xbb,
	0xb7, 0x46, 0xd0, 0xbc, 0xa2, 0x49, 0x5c, 0xc2, 0x78, 0xaf, 0x06, 0x63, 0xbd, 0x7b, 0x77, 0x6c,
	0x5c, 0x64, 0xce, 0x7f, 0x51, 0xa2, 0xf9, 0x9b, 0x03, 0x9d, 0x1a, 0xf5, 0xa1, 0xad, 0x49, 0x03,
	0xf3, 0x08, 0x4d, 0x5e, 0x33, 0x4a, 0x3f, 0xaf, 0xc1, 0xfb, 0x61, 0xf7, 0x07, 0x13, 0xe0, 0xe1,
	0x48, 0xfd, 0x9e, 0xb5, 0xc9, 0xaa, 0xe3, 0x4a, 0xc8, 0x5f, 0x3b, 0x30, 0xad, 0xd8, 0x0f, 0x4d,
	0xca, 0xe8, 0x3a, 0x47, 0x5e, 0x13, 0xe6, 0x4e, 0x0d, 0xe6, 0xf7, 0xbb, 0x5b, 0xd7, 0x84, 0xa9,
	0xb8, 0xbf, 0x04, 0xf8, 0x3b, 0x07, 0x66, 0x4c, 0x5f, 0x7b, 0x38, 0x31, 0xbb, 0x6b, 0x03, 0xe9,
	0x35, 0x21, 0x6e, 0xd5, 0x20, 0xde, 0xdf, 0xb8, 0xce, 0x45, 0xa3, 0x7f, 0x38, 0x30, 0x5b, 0x9f,
	0xf8, 0xd0, 0xf6, 0xa4, 0x3a, 0x18, 0x9d, 0x28, 0xbb, 0x4f, 0xbe, 0x93, 0x8f, 0x01, 0xfb, 0xe3,
	0x1a, 0xd8, 0x27, 0x68, 0x52, 0x3c, 0x23, 0xb5, 0xc5, 0x23, 0x7d, 0xe7, 0x1a, 0xfa, 0x9f, 0x1c,
	0x70, 0x6d, 0x33, 0x99, 0x48, 0x2e, 0x17, 0x3a, 0xdd, 0x44, 0x72, 0xb9, 0xd8, 0xa5, 0xfc, 0x0f,
	0x6a, 0x70, 0x1f, 0xa1, 0x07, 0x57, 0x93, 0xcb, 0xc0, 0x78, 0x2b, 0xa0, 0x3b, 0x4f, 0xe1, 0x76,
	0x44, 0x07, 0xd5, 0x81, 0x38, 0x4f, 0xce, 0x1f, 0xba, 0x33, 0x6b, 0x4e, 0x3d, 0x60, 0x54, 0xd0,
	0x03, 0xe7, 0x97, 0xae, 0xd5, 0x1c, 0xcf, 0xa8, 0x9f, 0x5c, 0x9f, 0xfc, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0x72, 0x8d, 0xfe, 0x1e, 0x16, 0x00, 0x00,
}
