// Code generated by protoc-gen-grpc-js-client
// source: metadata.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function metadataListRegions(p, conf) {
    path = '/_appscode/api/cloud/v1alpha1/regions/json'
    return xhr(path, 'GET', conf, p);
}

function metadataListZones(p, conf) {
    path = '/_appscode/api/cloud/v1alpha1/regions/' + p['region'] + '/zones/json'
    delete p['region']
    return xhr(path, 'GET', conf, p);
}

function metadataListBuckets(p, conf) {
    path = '/_appscode/api/cloud/v1alpha1/buckets/json'
    return xhr(path, 'GET', conf, p);
}

var services = {
    metadata: {
        listRegions: metadataListRegions,
        listZones: metadataListZones,
        listBuckets: metadataListBuckets
    }
};

module.exports = {appscode: {plow: {v1alpha1: services}}};
